### ISSUE TITLE
Module doesn't use mapping paths as Express

### ISSUE THREAD

**Issue by webmasterslava** [0b10011/UglifyJS-middleware#2]
Module doesn't use mapping paths as Express.

app.use(uglifyMiddleware(__dirname + '/my_theme_module', {}))
app.use('/js/my_theme', express.static(__dirname + '/my_theme_module/js'))

Express maps '/js/my_theme' http request to __dirname + '/my_theme_module/js' but this module doesn't do so and shows error "no such file or directory .../my_theme_module/js/my_theme"

**Comment by 0b10011** [comment]
Thanks, I'll take a look and try to get a fix in tonight!

**Comment by 0b10011** [comment]
@webmasterslava Sorry for the delay---I've taken a look and I believe it _does_ work. Try the following code instead:

``` javascript
app.use('/js/my_theme', uglifyMiddleware(dirname + '/my_theme_module/js', {}))
app.use('/js/my_theme', express.static(dirname + '/my_theme_module/js'))
```

That is, call `uglifyMiddleware()` just like you do `express.static()`. Let me know how it goes!
