### ISSUE TITLE
Incorrect source listed in generated JS source map file

### ISSUE THREAD

**Issue by delfuego** [0b10011/UglifyJS-middleware#3]
It appears that when a source map is generated by uglifyjs-middleware, the `sources` property of the resultant JSON map file is incorrect — it's a relative pathname rather than just a bare filename, and it's relative to my user home directory. As a result, for some reason Chrome (at least version 37.0.2062.3) and Firefox (at least ESR 24.6.0) don't play well with it; it's as if there's no source map file.

In other words, if I'm minifying a JS file that is being served from here:

`/home/delfuego/Downloads/node-dev/newapp/public/js/main.js`

then the source map file looks as follows:

``` json
{
"version": 3,
"file": "/js/main.map.js",
"sources": [ "Downloads/node-dev/newapp/public/js/main.js" ],
"names" : [ etc ],
"mappings": etc
}
```

When I use Firefox's dev tools to try to view the Javascript, I get the error `Cannot GET /js/Downloads/node-dev/cbiittag/public/js/main.js`, so clearly it's trying to load it at a URL based on that relative path...

**Comment by 0b10011** [comment]
Strange, I'll take a look, thanks for letting me know!

**Comment by 0b10011** [comment]
@delfuego Think this broke with the UglifyJS update (have a separate fork of it that fixes a few things necessary for this middleware). Fixed now. Could you try out the latest version (1.1.3) and see if it works for you? Thanks! (And sorry about the delay!)
